CREATE TABLE IF NOT EXISTS SEARCH_RESULT(
    ID INT AUTO_INCREMENT NOT NULL,
    CODE VARCHAR(50) NOT NULL,
    NUMBER INTEGER,
    FILENAMES VARCHAR(100),
    ERROR VARCHAR(100),
    PRIMARY KEY (id)
)