//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.01 at 07:51:52 PM MSK 
//


package inc.myself.models;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the inc.myself.models package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: inc.myself.models
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FilesWithNumberRequest }
     * 
     */
    public FilesWithNumberRequest createFilesWithNumberRequest() {
        return new FilesWithNumberRequest();
    }

    /**
     * Create an instance of {@link FilesWithNumberResponse }
     * 
     */
    public FilesWithNumberResponse createFilesWithNumberResponse() {
        return new FilesWithNumberResponse();
    }

    /**
     * Create an instance of {@link Result }
     * 
     */
    public Result createResult() {
        return new Result();
    }

}
